name: Coin Market update fetch Data

on:
  schedule:
    - cron: "*/1 * * * *" # 매 1분마다 실행
    # - cron: "0 9 * * *" # 매일 아침 9시 실행

jobs:
  fetch-and-store:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: fetchCoinMarketData
        run: node coinsGlobalAutoFetchData.js # JavaScript 파일 실행

      - name: Workflow complete
        run: echo "워크플로우 실행 완료"
